// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class TetsfTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new FirefoxDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void tetsf() {
    driver.Navigate().GoToUrl("https://www.tumblr.com/dashboard");
    driver.Manage().Window.Size = new System.Drawing.Size(1295, 695);
    driver.FindElement(By.CssSelector(".\\_3ntD6:nth-child(6) path")).Click();
    driver.FindElement(By.CssSelector("li:nth-child(1) > a > span:nth-child(1)")).Click();
    driver.FindElement(By.CssSelector(".\\_1DxdS:nth-child(1) .\\_33VXm:nth-child(6) svg:nth-child(1)")).Click();
    {
      var element = driver.FindElement(By.CssSelector(".\\_1DxdS:nth-child(1) .\\_33VXm:nth-child(6) svg:nth-child(1)"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Perform();
    }
    {
      var element = driver.FindElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element, 0, 0).Perform();
    }
    driver.SwitchTo().Frame(2);
    driver.FindElement(By.CssSelector(".has-text")).Click();
    {
      var element = driver.FindElement(By.CssSelector(".has-text"));
      js.ExecuteScript("if(arguments[0].contentEditable === 'true') {arguments[0].innerText = '<span>NewQuoteEdit</span>'}", element);
    }
    driver.FindElement(By.CssSelector(".editor-richtext")).Click();
    {
      var element = driver.FindElement(By.CssSelector(".editor-richtext"));
      js.ExecuteScript("if(arguments[0].contentEditable === 'true') {arguments[0].innerText = '<p>NewQuoteedit<br></p>'}", element);
    }
    driver.FindElement(By.CssSelector(".button-area")).Click();
    driver.SwitchTo().DefaultContent();
    driver.FindElement(By.CssSelector(".\\_1DxdS:nth-child(2) .\\_33VXm:nth-child(5) svg:nth-child(1)")).Click();
    {
      var element = driver.FindElement(By.CssSelector(".\\_1DxdS:nth-child(2) .\\_33VXm:nth-child(5) svg:nth-child(1)"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Perform();
    }
    {
      var element = driver.FindElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element, 0, 0).Perform();
    }
    driver.FindElement(By.CssSelector(".\\_16Les:nth-child(2) > .Hi_aW")).Click();
  }
}
